name: truck
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.3.0
  icons_plus: ^4.0.0
  flutter_native_splash: ^2.3.8
  lottie: ^2.7.0
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.3
  flutter_tts: ^3.8.5
  http: ^1.1.2
  path_provider: ^2.1.1
  intl_phone_number_input: ^0.7.4
  open_filex: ^4.3.4
  file_picker: ^6.1.1
  mime: ^1.0.4
  image_picker: ^1.0.4
  social_media_recorder: ^1.1.12
  voice_message_package: ^2.1.2
  firebase_ui_firestore: ^1.5.15
  chat_bubbles: ^1.5.0
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  hive: ^2.2.3
  in_app_notification: ^1.1.2
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
