name: truck
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.3.0
  icons_plus: ^4.0.0
  awesome_snackbar_content: ^0.1.3
  flutter_native_splash: ^2.3.6
  lottie: ^2.7.0
  hive: ^2.2.3
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.3
  flutter_tts: ^3.8.5
  http: ^1.1.2
  path_provider: ^2.1.1
  intl_phone_number_input: ^0.7.4
  open_filex: ^4.3.4
  file_picker: ^6.1.1
  flutter_chat_ui: ^1.6.10
  mime: ^1.0.4
  image_picker: ^1.0.4
  social_media_recorder: ^1.1.12
  voice_message_package: ^2.1.2
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
