name: truck
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.3.0
  icons_plus: ^4.0.0
  awesome_snackbar_content: ^0.1.3
  flutter_native_splash: ^2.3.6
  chatview: ^1.3.1
  lottie: ^2.7.0
  text_to_speech: ^0.2.3
  audio_waveforms: ^1.0.4
  hive: ^2.2.3
  http: ^1.1.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.3
  firebase_pagination: ^3.0.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
